version: '3.9'

services:
  pacoca-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
